### ISSUE TITLE
memorystream 0.3.0 breaks compatibility with node 0.10.x

### ISSUE THREAD

**Issue by MaxMotovilov** [JSBizon/node-memorystream#11]
```
var m = new (require( 'memorystream' ))( null, { readable: false } );

process.stdin.pipe( m ).once( 'end', function() {
	console.log( m.toString() );
} );
```

Works in 0.2.0 but not in 0.3.0 (node 0.10.25 in both cases).

**Comment by JSBizon** [comment]
This is because writable streams for node 0.10.x doesn't have event 'end' :  http://nodejs.org/api/stream.html#stream_class_stream_writable. 

Instead of 'end' need to use 'finish' event. This code have to work:

```javascript
var m = new (require( 'memorystream' ))( null, { readable: false } );

process.stdin.pipe( m ).once( 'finish', function() {
    console.log( m.toString() );
} );
```

**Comment by MaxMotovilov** [comment]
Thank! This behavior appears consistent with other streams, e.g. `createWriteStream`
