### ISSUE TITLE
Basic I/O Operation working as intended?

### ISSUE THREAD

**Issue by r0b5t4** [JSBizon/node-memorystream#12]
Running the "Basic I/O Operation" from https://www.npmjs.com/package/memorystream the output is "World!". Is this intended? The chunk "Hello" passed to the initialization of the memory stream is not emitted on "data". Thanks for clarification. 

    var MemoryStream = require('memorystream');
    var memStream = new MemoryStream(['Hello',' ']);
    
    var data = '';
    memStream.on('data', function(chunk) {
        data += chunk.toString();
    });
    
    memStream.write('World');
    
    memStream.on('end', function() {
        // outputs 'Hello World!'
        console.log(data);
    });
    memStream.end('!');

**Comment by JSBizon** [comment]
hmm, looks this is a bug for Duplex streams will fix quick

**Comment by r0b5t4** [comment]
One more question, is the stream supposed to hold data if there is no listener? Should this snippet write back "foo bar "?

    
    var MemoryStream = require('memorystream');
    var stream = new MemoryStream();
    
    stream.write("foo ");
    stream.write("bar ");
    stream.end();
    
    console.log(stream.toString());

**Comment by JSBizon** [comment]
actually no, because you created Duplex(readable and writeable) stream. For hold data you might use writeable stream:

var stream = new MemoryStream(null, {readable: false});//MemoryStream.createWriteStream();

stream.write("foo ");
stream.write("bar ");
stream.end();

console.log(stream.toString());

**Comment by JSBizon** [comment]
Do you want option for hold data for duplex stream too? I can implement it while will fix bug :)

**Comment by r0b5t4** [comment]
No need to implement it just for me, the clarification is enough. Many thanks.

**Comment by JSBizon** [comment]
fixed
